# pod template
apiversion: v1
kind: pod
metadata:
  name: multi-pod-pass
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    -  containerport: 80
  - name: c2
    image:  ravi2krishna/nodejs-api
    ports:
    - containerport: 8080